title: Just Codes
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: "http://localhost:4000"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Início
   url: /index.html
 - title: Sobre
   url: /about
 - title: Contato
   url: /contact

social:
   github: justcodes
   email: emalherbi@gmail.com
   #twitter: brianmaierjr
   #facebook: brianmaierjr

google_analytics: "UA-58263416-1"
